name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
        
      - name: Compile English LaTeX document
        uses: xu-cheng/latex-action@v4
        continue-on-error: true
        with:
          root_file: english.tex
      
      - name: Compile Spanish LaTeX document
        uses: xu-cheng/latex-action@v4
        continue-on-error: true
        with:
          root_file: spanish.tex

      - name: Upload English PDF file
        uses: actions/upload-artifact@v6
        with:
          name: PDF-English
          path: english.pdf

      - name: Upload Spanish PDF file
        uses: actions/upload-artifact@v6
        with:
          name: PDF-Spanish
          path: spanish.pdf
